title: "AI4ALL NHANES Project Documentation"
description: "Documenting procedures and results related to AI4ALL NHANESProject."
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
  "GitHub Repository":
    - "https://github.com/isabelle926/siads697"
aux_links_new_tab: true
markdown: kramdown
back_to_top: true
back_to_top_text: "Back to top"
